### PR TITLE
fix: remove dependency on pkg_resources, moving to implicit namespaces

### PR DESCRIPTION
**Pull request by jsaladev**
pkg_resources.declare_namespace is deprecated, going for the native/implicit namespaces (PEP 420) is a much better option according to [setuptools](https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages)

Fixes issue #140

### CODE REVIEW

**Comment by aqeelat** [comment]
@clundin25 can we do the same thing we did in https://github.com/googleapis/google-auth-library-python/pull/1205 here?

**Comment by clundin25** [comment]
@parthea PTAL

**Comment by aqeelat** [comment]
@parthea @clundin25 any updates?

**Review by parthea — CHANGES_REQUESTED** [review]
Please make a change similar to the one in https://github.com/googleapis/google-auth-library-python/pull/1205

**Comment by parthea** [comment]
Fixed via #187

**Pull request closed without merging**
